DROP TABLE IF EXISTS tb_user;

CREATE TABLE tb_user(
    id INT(11) PRIMARY KEY  AUTO_INCREMENT COMMENT 'id',
    username VARCHAR(30) NOT NULL UNIQUE COMMENT '用户名',
    pwd VARCHAR(10) NOT NULL COMMENT '密码',
    salary  INT  NULL DEFAULT 0 COMMENT '薪资'
);
